### ISSUE TITLE
Hot reload doesn't work with type definitions

### ISSUE THREAD

**Issue by BastinJafari** [jina-ai/dashboard#109]
**Describe the bug**
When editing type definitions, the hot reloading feature for developing doesn't work. One has to restart the dev server manually with npm run start-dashboard

**Comment by BastinJafari** [comment]
Btw, that happens only if the file just contains type definitions. 
For example if one edits src/components/Hub/types.ts

**Comment by rjgallego** [comment]
Hello, I'd like to look into this if it's still an issue.

**Comment by BastinJafari** [comment]
Hi :)
Yes, it is still an issue!
Thank you very much for looking into it.

**Comment by rjgallego** [comment]
I found this article that does a good job of explaining how the hot reload is implemented in React: [https://reactnative.dev/blog/2016/03/24/introducing-hot-reloading](url)
I'm assuming the application is only using hot reload implemented with React as I didn't see any other package or Webpack being used for this purpose?

In a nutshell, what I think is happening is that the application is caching the type definitions exported in type.js file and is using the cached version whenever the application is recompiled. But when a change is made to a file that imports the type, the application is forced to re-cache those exports to ensure it has the latest version. I tested this using the types defined for the LogStream, changing the types.js file doesn't do anything initially but if I save a change to a file that uses those type definitions (i.e. LogLevelSummaryChart.tsx) both are hot-reloaded and the change is reflected. 

So, it looks like we need to find a way to force React to re-cache the type definitions exported in the types.js files on save. Still looking to see how / if it is possible to do this.

**Comment by rjgallego** [comment]
I've been researching this issue for several days, not sure if there really is a solution. There are several files that don't hot-reload, only ones that directly affect the user interface will cause the application to compile on save.

I assume that if you are changing a type definition you will also have to update the files that use that type, so if you want the type changes to take place without restarting the dashboard you can make changes to the types.js files first then update the tsx files that use that type, then both will be re-compiled on save.

**Comment by Roshanjossey** [comment]
@rjgallego, thank you for looking into this. This project is created with [Create React App](https://create-react-app.dev/)(CRA). Most of the configuration including webpack config is in react-scripts. So, this is probably a problem with hot reload in CRA. I know React frameworks like Next.js has good implementations of hot reload. My assumption is that hot reload of CRA is still not there.

**Comment by BastinJafari** [comment]
@rjgallego Thanks a lot for your effort! Until we find a proper solution, your little hack will be still very helpful :)
