### ISSUE TITLE
🧪 Create integration tests for LogsTable

### ISSUE THREAD

**Issue by Roshanjossey** [jina-ai/dashboard#110]
🧪 This is the view that should be tested

![Screenshot from 2021-01-12 12-39-36](https://user-images.githubusercontent.com/8488446/104311330-f24b1300-54cc-11eb-9e54-cfefb12f2a01.png)

## 💻  How to run this project locally

1. Fork this repository by clicking on fork button on the top right. This will create a copy of this repository on your account.
2. Clone your fork.
Get the URL of your fork by clicking on `code` button on GitHub.
Clone it to your local with command `git clone <URL you copied>`

    `git clone <https://github.com/><your-username>/dashboard.git`.

3. Install dependencies using command `npm i`.
```
cd dashboard
npm i
```
4. Run dashboard via the following ways .

### Run in the debug mode

1. `npm run start_dev-server`

    testServer will be running on `http://localhost:5000` by default

2. `npm run start-dashboard`

    Dashboard will be served on `http://localhost:3000` by default

## 🏃‍♀️ How to get there.
Click on the option `Log Stream` from the sidebar on the left

The components of interest are [LogsTable](https://github.com/jina-ai/dashboard/blob/master/src/components/LogStream/LogsTable.tsx) and [LogsTableHeader](https://github.com/jina-ai/dashboard/blob/master/src/components/LogStream/LogsTableHeader.tsx)

## 🧪  How to run integration tests

Run `npm run cy:dev` from your console. This will open cypress and you can run the test suites you want to run by clicking on it.

When you're done working, make sure that `npm run cy:run` passes without any errors.

## 📝 Where to make changes?

In `cypress/integration/views` directory and in the components you want to test.
Check [this pull request ](https://github.com/jina-ai/dashboard/pull/104)

Pay attention to the changes in files `cypress/integration/views/logsView.ts` and `src/components/LogStream/BarChartBase.tsx`. You'll have to make similar changes.

## 📖 How to learn about writing integration tests?

We use a framework called [cypress](https://cypress.io/) for integration tests. Their documentation is quite helpful.
Go through their [best practices](https://docs.cypress.io/guides/references/best-practices.html), [interacting with elements](https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Actionability), [structuring tests](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Test-Structure) and you'll get a great understanding of how to write good integration tests

## 🖐️ I want to work on this.

If you're interested in working on this issue, please write a comment down below. 💬

If you need any help or have questions, you can ask questions here or ask in our [slack group](https://join.slack.com/t/jina-ai/shared_invite/zt-dkl7x8p0-rVCv~3Fdc3~Dpwx7T7XG8w)

**Comment by ravishankarste** [comment]
I am interested in working on this issue.

**Comment by Roshanjossey** [comment]
Hi @ravishankarste, thank you for your interest. Try running this project locally by following the steps in the issue description. If you run into any problems or have questions about the issue, you can ask here.

**Comment by ravishankarste** [comment]
Hi,

Thank you..I am trying to run the project..Surely, if I have questions, I
will ask.

Best regards
Ravi
