### ISSUE TITLE
Typo in dev-resources/examples/hello-world-gradual.json

### ISSUE THREAD

**Issue by BastinJafari** [jina-ai/dashboard#119]
**Describe the bug**

There is a typo in the hello world json for the dev server 

https://github.com/jina-ai/dashboard/blob/master/dev-resources/examples/hello-world-gradual.json

Instead of levelname it should be levelName.

Therefore it's also wrong in the whole codebase

**Comment by DavidSanwald** [comment]
I only had a quick look at the backend and do not want to go through all the trouble installing fluentd ruby gems etc. on my system to get things running (just docker containers would have been okay), so I might be wrong but it looked like the backend is still not camel casing `levelname`.

**Comment by Roshanjossey** [comment]
With #140, this is changed to `level`.

From what I understand, jinaD is doing this conversion. @imsergiy, could you please confirm this?
