### ISSUE TITLE
start-dashboard script error on Windows

### ISSUE THREAD

**Issue by rjgallego** [jina-ai/dashboard#147]
**Describe the bug**
Running `npm run start-dashboard` script produces an error on Windows when trying to run `REACT_APP_TARGET=dashboard`

**Have you solved it? If so, let us know how!**
Windows has to use the SET command to set environment variables. Below script works on my machine for starting the dashboard.

`"start-dashboard": "SET \"REACT_APP_TARGET=dashboard\" && react-scripts start"`

Thinking this command could be added to the package.json file as a separate script, something like `"start-dashboard_win"`. 

---

**Screenshots and logs**
<img width="457" alt="Capture" src="https://user-images.githubusercontent.com/59635994/106296888-1154df00-6207-11eb-9229-f7ca81fe55fc.PNG">

**Comment by Roshanjossey** [comment]
Thank you for opening this bug and your suggestion to solve it @rjgallego :+1: 

I'll try this command on linux. Ideally, we would like to have a single script that runs both on windows an *nix OSes.

**Comment by DavidSanwald** [comment]
https://www.npmjs.com/package/run-script-os

but since it's coming from me, you better think twice about using it.
@hanxiao was always been worried about the negative impact of neurodiversity on jina ai, so I don't know :P

**Comment by Roshanjossey** [comment]
@DavidSanwald, thank you for your suggestion. I'll checkout run-script-os. Initially I had [cross-env](https://www.npmjs.com/package/cross-env) in mind to solve this.

Meanwhile, @rjgallego, I've created a branch with a temporary solution for this. Please try it out and tell me if it works for you.
You can pull my changes with the following commands.

```
git checkout -b Roshanjossey-fix/start-dashboard-error-on-windows master
git pull https://github.com/Roshanjossey/dashboard.git fix/start-dashboard-error-on-windows
```

If we see a pattern of these problems repeating, I'll spend some time to try and use one of the packages suggested above.

**Comment by rjgallego** [comment]
@Roshanjossey I pulled your branch, the start-dashboard script brings up the dashboard but it's producing the below syntax error: 

![image](https://user-images.githubusercontent.com/59635994/106395780-f2964a00-63b8-11eb-9cb2-1dab341bce26.png)

**Comment by Roshanjossey** [comment]
@rjgallego, this will happen if the major versions of @emotion/react @emotion/core and @emotion/styled aren't the same. I've seen this when @emotion/react version was 11.x.x when @emotion/core version was 10.x.x. 

Please try running  `npm install`

I'll check package-lock.json on my branch to see if versions are correct.

**Comment by Roshanjossey** [comment]
I checked package-lock.json and versions looks alright. Make sure you run `npm install`

**Comment by rjgallego** [comment]
Thanks, that fixed it. I'm able to run the dashboard with the same start-dashboard script now.

**Comment by Roshanjossey** [comment]
Thank you for your feedback @rjgallego. 

#149 is merged. Closing.
