### ISSUE TITLE
Add 2nd Hub endpoint to allow metadata updates

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#212]
Allow for the user to update only the description or metadata of the Hub image (not uploading a new docker image)

<p></p>

The metadata of the image should change while still linking to the same docker image.

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7073180

**Comment by aga11313** [comment]
This issue is not relevant as requirements have changed
