### ISSUE TITLE
Storage Lambda function setup

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#215]
We can work directy on the cloud. Setting up CI/CD for NodeJs is required.

## **Acceptance Criteria**

- Set up lambda function instance to interface with MongoDB

- Configure according to the design document on frontend/backend coms

<p></p>

Set up for the lambda function to handle API endpoints.

<p></p>

**Testing of the individual functions**

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7126730

**Comment by imsergiy** [comment]
https://github.com/jina-ai/console-web-functions
