### ISSUE TITLE
Sync github labels and github project board columns

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#226]
From March 2021, will be moving all issue tracking from Jira to Github. We will be using Github projects kanban boards to track the status of tickets. 

**The product team would like a feature that:** 

When a GitHub issue is moved between Github project board columns that GitHub issue labels be automatically updated. We have issue labels that match each project board column [status:to_do,status:in_progress]. Currently, we would have to manually move the ticket between columns, and update the label. 

<p></p>

<p></p>

**The reason for this**

Project boards will be private, only shown to Jina team members. But we would still like community members should be able to use the labels to see the status of their feature requests. 

<p></p>

Check out this project as a possible solution <https://github.com/doerfli/github-project-labels>
https://github.com/isaacs/github/issues/1488
<img width="364" alt="Screenshot 2021-03-24 at 14 43 30" src="https://user-images.githubusercontent.com/59612379/112320626-7846bf80-8caf-11eb-91c1-343b539a5acc.png">

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7160519

**Comment by FionnD** [comment]
@Roshanjossey could you provide a very quick summary of why this [solution](https://github.com/doerfli/github-project-labels) will not work?

**Comment by FionnD** [comment]
See here, https://github.com/isaacs/github/issues/1488 

A solution will need to be coded which merged graphql and the webhooks

**Comment by aga11313** [comment]
@niuzs-alan Could take this over in the coming weeks
