### ISSUE TITLE
pod api endpoint

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/dashboard#23]
https://github.com/jina-ai/jina/pull/335

very first version of the pod api export, available at `/data/api/pod` (logserver.default.yml)

It returns `{'pod': d, 'version': jina_version, 'usage': pod_cli_usage}`, where `d` is the 'help', 'choices', 'default' and 'type' of each arg.

Limits:
- enum is stringify to int and becomes 0,1,2... semantics are lost
- default is only for reference, as some random default args will give random value everytime you call it.

**Comment by Roshanjossey** [comment]
@imsergiy, is this issue still relevant as logs will be moved to jinad?

**Comment by imsergiy** [comment]
@Roshanjossey 

We can close this
