### ISSUE TITLE
Authentication issue when self hosting the dashboard

### ISSUE THREAD

**Issue by kazanture** [jina-ai/dashboard#24]
Hi @hanxiao,
I am new to jina-ai but I decided to spend more time to play with it and hopefully contribute with PRs(appreciate any recommendation about which repo to start).
I have tried to host the dashboard on my localhost following the doc but I am having an authentication issue.
I followed the code and it looks like the github authentication goes through jina hub url.
And when it returns successfully it redirects to jina ai dashboard instead of localhost dashboard.

So I have a few questions:
- Why is the authentication is part of hub but not dashboard if this is a standalone project?
- Should I also run hub locally to be able to host the dashboard?(I will try this after posting this but writing here on parallel maybe I can gain some time:))

Or am I missing something?
Thanks

**Comment by kazanture** [comment]
Ok I guess as far as I understand to be able to self-host dashboard; I need to start hubAPI with my own config.js. I will try this and see if it works.

**Comment by imsergiy** [comment]
Since the hub uses GitHub authentication for interacting with content (ratings, reviews) the origin for the hub API is restricted to `https://dashboard.jina.ai`. Aside from the hub, the rest of the dashboard does not require authentication and will work properly on a different origin.
