### ISSUE TITLE
Change boolean typed text input in pod properties to on/off switches

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#243]
# Feature Request

As a user, I want to be able to change Pod properties by toggling a switch rather than typing true/false into a boolean text field

# Acceptance Criteria

- This ticket is done when: The user can change all true/false properties of a Pod by toggling an on/off switch.

- This ticket is done when: the user can still save the configuration of properties and return to it later (positions of toggles are saved)

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7159937

**Comment by aga11313** [comment]
![image](https://user-images.githubusercontent.com/23415764/110451622-a8de0500-80c4-11eb-80f0-58c1bf80a9b2.png)

**Comment by franquil** [comment]
Hi Jina team, could someone assign the issue to me? I'll give it a go. @lusloher @aga11313

**Comment by aga11313** [comment]
@franquil Done :) once you get started on a pr please link it to this isuue
