### ISSUE TITLE
Generate ActionTypes dynamically

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#244]
# Maintenance
Right now you have to write down the action types manually like

<p></p>

`export type FlowActionTypes =

| LoadFlowAction

| CreateNewFlowAction

| UpdateFlowChartAction

| UpdateSelectedFlowAction

| DuplicateFlowAction

| DeleteFlowAction

| UpdateNodeAction

| DeleteNodeAction

| RerenderAction

| ImportFlowAction

| SetFlowArgumentsAction`

<p></p>

It would be nice to generate this type dynamically out of an object or a list.

# Acceptance Criteria
* This ticket is done when: complex types like this are automatically generated from an object or a list
* This ticket is done when: this change is tested appropriately

<p></p>

<p></p>

**Good community issue**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200498922555298/1200501077921467) by [Unito](https://www.unito.io)

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7073106

**Comment by DavidSanwald** [comment]
You should not pluralize your Types like that.
A reducer expects a flow action, this can be read as "action of type FlowAction". 
If you pluralize `ImportFlowAction` as  Type `FlowActionTypes` but it's just one action and therefore of type `FlowAction`.

Another really simple example: 
No one would consider pluralizing booleans, even though there are two values, that are of type Boolean.

Apart from that:
You should use the following pattern here.

`const flowActions = ['CreateFlowAction', 'LoadFlowAction', ... ] as const`
You assert as const, to prevent type widening to `string[]`
To turn it into a union type, like the one above can now be done by just doing
`type FlowAction = typeof flowActions[number]`

**Comment by DavidSanwald** [comment]
To clarify things:
There are some actual problems, that can be caused by naming types that way.
But in the long run, renaming the Types doesn't matter as much. Leaving behind the mental model, that is related to that naming pattern, will be more relevant for advancing the codebase.

**Comment by AvTe** [comment]
I encountered the exact same issue with NGRX - too much repetetive boilerplate code for actions as well as for reducers.

you can generate classes named dynamically like this:

`const ClassFactory = (className) => {
    const obj = {};
    obj[className] = class { };
    return obj[className];
};

const classA = ClassFactory('classA');`

**Comment by aga11313** [comment]
@BastinJafari @Roshanjossey  has this progressed any further than the above discussion?
