### ISSUE TITLE
Add staging environment

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#245]
# Feature Request | Maintenance

The developers want to push to a development branch first before merging into master.

# Acceptance Criteria

- This ticket is done when: a separate development branch is established

- This ticket is done when: this development branch builds, runs tests etc just like the master branch

- This ticket is done when: a process around merging into the master branch (on release) is established. ie. when we merge, how and who is responsible

@deepankarm  help needed to set up domains

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7188843

**Comment by deepankarm** [comment]
Setup https://console-dev.jina.ai/
