### ISSUE TITLE
add support to the multiple selection box

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/dashboard#25]
It will be more convenient if we can select **multiple pods** by **clicking and holding the mouse**. Currently, it is impossible to move several pods at the same time.

**Comment by DavidSanwald** [comment]
This functionality (same goes for #26) does require updates to ["@mrblenny/react-flow-chart"](https://github.com/MrBlenny/react-flow-chart). Would you consider a fork? 
What I'd propose:
If the maintainer of react-flow-chart signals, that he would be generally fine to include this functionality back into the project, it would be worth forking.

One additional question:
The described behavior to multi-select a group of PODs would be incompatible with the current functionality:
At the moment a dragging behavior moves the whole canvas.
Two options: 
1. Going without the functionality to multi-select by dragging a selection box around nodes. Instead at least allowing multi-select, by selecting nodes by click and holding down the shift key at the same time.
2. Without any pressed key, dragging has the usual behavior and moves the whole canvas but with a pressed modifier key, it draws a selection box.

**Comment by xiqi** [comment]
I created a [pull request](https://github.com/MrBlenny/react-flow-chart/pull/204) to add this feature to the "react-flow-chart" package. While waiting for the original maintainer to accept and include it into the next release, feel free to use [my fork](https://github.com/xiqi/react-flow-chart).

**Comment by imsergiy** [comment]
https://github.com/jina-ai/dashboard/pull/71
