### ISSUE TITLE
Implement sending API requests to the Jina gateway

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#253]
# Feature Request

As a user, I want to be able to index data through the running Flow.  Frontend should be able to send json bodies via POST requests/websocket streams. 

<p></p>

This ticket requires figuring out how we create jsons from files/text.

<p></p>

<p></p>

# Acceptance Criteria

- This ticket is done when: pressing the play button uploads all the files to the workspace

- This ticket is done when: the Index Flow is started and terminated once all the files are indexed

- This ticket is done when: the Query Flow is started and the example page is opened

<p></p>

<p></p>

<p></p>

<https://api.jina.ai/rest>

![](https://a.slack-edge.com/production-standard-emoji-assets/13.0/google-medium/1f446.png)

This is for all the apis related to indexing/querying.

<p></p>

<https://api.jina.ai/daemon/>

![](https://a.slack-edge.com/production-standard-emoji-assets/13.0/google-medium/1f446.png)

This is for all the apis related to flow creation/termination

<p></p>

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7271365

**Comment by BastinJafari** [comment]
Tasks to do:

- update data structure to include workspaces
- implement file uploading to workspaces 
- implement tabs for flowView
- add endpoint uri to flow state
- double clicking the gateway opens indexing file upload modal

**Comment by aga11313** [comment]
As discussed the data ingest itself will now look like this:

- a special crafter will be used for each example with a URL to an s3 bucket
- user will upload the files to the s3 bucket
- the crafter will pull files for indexing directly from the s3 bucket

**Comment by aga11313** [comment]
@deepankarm update the crafter python file in order to use the correct csv file
