### ISSUE TITLE
Dataset download and streaming

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#257]
Store python files as string and send to workspace.

Add the requests to 

# Acceptance Criteria

- This ticket is done when: dataset download is enabled as a zip file

- This ticket is done when: we have a way to stream the whole file to the jina gateway

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7284093

**Comment by aga11313** [comment]
Currently done for the multimodal example:

Can extend by:
- [ ] chatbot example
- [ ] kicking off a conversation on generalized data ingest

**Comment by nan-wang** [comment]
> This ticket is done when: dataset download is enabled as a zip file

What is the purpose of this goal?
