### ISSUE TITLE
Cypress: Avoid detached Element without using { force: true } 

### ISSUE THREAD

**Issue by BastinJafari** [jina-ai/dashboard#265]
In our cypress test for flowView, the settings button gets detached from the DOM:

![image](https://user-images.githubusercontent.com/25417797/111622463-84330d00-87e9-11eb-9d3b-9bf5144715ae.png)

In order to fix it, we use

` cy.dataName("settingsButton").click({ force: true })`

Cypress though suggests avoiding using { force: true }.

We should find out what causes this and fix it accordingly.

**Comment by aga11313** [comment]
Created a copy of this in #267 so closing
