### ISSUE TITLE
Dashboard plot does not match with yaml file (helloworld multimodal's flow-index.yml)

### ISSUE THREAD

**Issue by Kelton8Z** [jina-ai/dashboard#266]
**Describe the bug**

helloworld multimodal's flow-index.yml does not show correctly once pasted to Jina Dashboard

**Have you solved it? If so, let us know how!**

---

**Environment**

**Screenshots and logs**
<img width="1158" alt="dashboard_yaml_mismatch" src="https://user-images.githubusercontent.com/22567795/111725142-7a6ce080-88a1-11eb-882c-34fee6045f4b.png">

**Comment by aga11313** [comment]
Created a copy of this with #268 so closing this one @Kelton8Z
