### ISSUE TITLE
Cypress: Avoid detached Element without using { force: true }

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#267]
Cypress: Avoid detached Element without using { force: true }

<p></p>

In our cypress test for flowView, the settings button gets detached from the DOM:

<p></p>

![image](

![](https://user-images.githubusercontent.com/25417797/111622463-84330d00-87e9-11eb-9d3b-9bf5144715ae.png)

)

<p></p>

In order to fix it, we use

<p></p>

` cy.dataName("settingsButton").click({ force: true })`

<p></p>

Cypress though suggests avoiding using { force: true }.

<p></p>

We should find out what causes this and fix it accordingly.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200498922555298/1200500945623398) by [Unito](https://www.unito.io)

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7392714

**Comment by franquil** [comment]
I couldn't find Cypress's recommendation regarding to 'avoid using `{force: true}`'. At this [page](https://docs.cypress.io/guides/core-concepts/interacting-with-elements#Forcing), it says *"You can pass { force: true } to most action commands."*
