### ISSUE TITLE
Decompose Settings .jsx into small components

### ISSUE THREAD

**Issue by MenaiAla** [jina-ai/dashboard#29]
I've checked [Settings.js](https://github.com/jina-ai/dashboard/blob/master/src/components/Settings/Settings.jsx) which supposed to be ( maybe) SettingsCard as a name of the file.

I find that component is complex and it does many things and I suggest decomposing it into small components that do one thing ( SRP) ( Header, Body, Footer) because it's a Card.  This will make scaling easy in the future and will help you maintain the Unit Test in decomposable files and in Isolation.

**Comment by DavidSanwald** [comment]
SRP originally demanded that every module should have one, and only one reason to change. 
It's quite different from "doing only do one thing".

The current dashboard already uses a library that provides an abstraction for a card header. 
Maybe you can provide an example of how your components would look like and where tey would be different from the used layout components.

I love this article, to me, there's no better guideline for understanding reasonable principles for boundaries between components:
https://jxnblk.com/blog/defining-component-apis-in-react/

What's your opinion about it? Does it seem reasonable in the context of this project? What structure would you suggest?

**Comment by DavidSanwald** [comment]
Solved by the linked PR. Thank you for your input.

**Comment by MenaiAla** [comment]
You welcome.
