### ISSUE TITLE
Update details page to correctly pull README

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#297]
## Acceptance criteria:

- the README for all the Hub Images is correctly populated with the README of that Image

- all 7 types of executors are handled

- [x] crafters
- [x] rankers
- [x] indexers
- [x] segmenters
- [x] encoders
- [x] classifiers
- [x] evaluators

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7471108

**Comment by aga11313** [comment]
Lets split this up:

- [ ] crafters - @BastinJafari 
- [ ] rankers - @imsergiy 
- [ ] segmenters - @deepankarm 
- [ ] classifiers - @Roshanjossey 

An example of the kind of change we need: https://github.com/jina-ai/jina-hub/pull/7578

REMEMBER TO BUMP THE VERSION NUMBER when changing the url

**Comment by aga11313** [comment]
@JoanFM if you can take the Segmenters that would be great :)

**Comment by JoanFM** [comment]
I did a quick look and updated I think everyone missing in 2 PRs

**Comment by JoanFM** [comment]
jina-ai/jina-hub#7792 jina-ai/jina-hub#7791

**Comment by JoanFM** [comment]
Is the only problem handled here the link in the `url`?

**Comment by aga11313** [comment]
Yeah I think so @Roshanjossey, what was the rationale behind doing this in multiple PRs?

**Comment by JoanFM** [comment]
The tests are better handled in multiple PRs, but we can do it once at batch, and next `dependabot` update will expose the right value.

If we do it in these 2 PRs, not all the images will be built, but we can have a batch and will quickly be updated, and will imply less engineering effort
