### ISSUE TITLE
Update the Hub details section with other install commands

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#298]
Designs: https://www.figma.com/file/cpwSWL4lu327RXW0PavsoZ/Jina-Console-UI?node-id=1082%3A3056

Add other instructions to the right hand side bar:

- docker pull (already exists)

- How this pod can be used in the CLI. → same structure just insert the name of the Image to a template command

- How this pod can be used in a Flow → same structure just insert the name of the Image to a template command

<p></p>

## Acceptance criteria:

- each Hub image has 3 commands

- each command is restyled

- each command has a copy button next to it

<p></p>

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7510378

**Comment by aga11313** [comment]
This issue is now part of #299
