### ISSUE TITLE
Adding a new workspace adds a new Flow as well

### ISSUE THREAD

**Issue by aga11313** [jina-ai/dashboard#303]
**Describe the bug**

Clicking on the button to add a new Workspace also creates a new Custom Flow within that workspace.

**Have you solved it? If so, let us know how!**

---

**Environment**

**Screenshots and logs**

![addworkspace](https://user-images.githubusercontent.com/23415764/115412317-7ca1c200-a1f4-11eb-99c3-34c70a26dace.gif)

**Comment by franquil** [comment]
What's the expected behaviour? Shall a new 'custom flow' created at the Wordspace that just being created instead of the one that currently selected? @aga11313

**Comment by aga11313** [comment]
Expected behavior:

1. New workspace button only adds a new Workspace (currently this button adds both a new Workspace and a new Flow)
![image](https://user-images.githubusercontent.com/23415764/115534520-28e8b480-a298-11eb-9758-41126a5f157a.png)

2. New Flow button only adds a new Flow
![image](https://user-images.githubusercontent.com/23415764/115534571-343be000-a298-11eb-918b-a496d791ace3.png)

**Comment by franquil** [comment]
@aga11313 So the new created Workspace will be empty? Looks like the code deliberately created a default 'custom flow' when creating a workspace, however, it failed to set `selectedWorkspaceId` attribute which leads to the new 'custom flow' being created at the wrong workspace.

**Comment by aga11313** [comment]
Yeah you are correct, there should be a new Flow created but currently that is happening in the wrong workspace. Each new workspace should have a default Flow created inside it.

**Comment by franquil** [comment]
@aga11313 Another thing I wonder is that the newly created workspace shall be selected after creating, or the one that being working on shall be selected. Looks like the former is expected behaviour? I suppose I can sort the issue out.

**Comment by aga11313** [comment]
The new workspace should be selected

**Comment by franquil** [comment]
Looks like PR #304 fixed this issue.
