### ISSUE TITLE
Reaserch into rendering frameworks (Cookiecutter)

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#316]
Explore and choose a rendering framework that would be appropriate to use for the  new cookie-cutter implementation.

## Acceptance criteria

- A list of explored frameworks with pros, cons listed

- A recommendation in terms of which framework should be used for our implementation

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7726722

**Comment by BastinJafari** [comment]
If there are no special requirements for the templates, I would go for the most popular templating engine, which is handlebarjs.  Researching pros and cons doesn't make real sense if we don't have requirements to measure against.
