### ISSUE TITLE
Create a form to input user image metadata

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#320]
Utilising json schema to create a user input form for creating a new image (the Json schema definition itself has been worked on by Kelton, check with him what has already been done) --> <https://github.com/jina-ai/jina-hub/issues/7459>

<p></p>

Form design (this document describes the different fields that the user can enter and the type of inputs we expect) --> <https://docs.google.com/document/d/1Uxfz0TjqfDEPwXyyM_T3TASadQDWz4hWeKPPmxcs9YM/edit>

<p></p>

![Screenshot 2021-05-17 at 12 56 58](https://user-images.githubusercontent.com/23415764/118477832-6c0b3b80-b70f-11eb-8d67-75031b95cc38.png)

<p></p>

<p></p>

Designs for this should be available on the 19/05/2021

<p></p>

* User fills out the form which is validated on input.
* A template is pulled from the Jina repo
* fields in the template are replaced with the user input --> here a templating library needed

## Acceptance criteria:
* create a screen which allows the user to enter basic details about the new image they want to create according to the designs and the PM specification
* utilize json schema to validate the inputs on input
* pull template repository and replace files

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200498922555298/1200501017796828) by [Unito](https://www.unito.io)

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7616975

**Comment by aga11313** [comment]
Irrelevant due to priority changes
