### ISSUE TITLE
Replace the deprecated API endpoint in Jina Box

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#335]
Upgrade box to 2.0 to unblock <https://jinaai.slack.com/archives/C01AE0X9V19/p1622215674010300>

<p></p>

There was a Flask based API endpoint that should be removed.

<p></p>

Tasks:

* [x] use the correct (non depracated) endpoint
* [x] handle the api response in the new way
* [x] compile the code into a package
* [x] upload the package to the index

## Acceptance criteria:
* Jinabox should talk to the correct endpoint.
* Jinabox should correctly parse the new 2.0 data structure
* Jinabox should work with 2.0 examples

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200498922555298/1200500936217885) by [Unito](https://www.unito.io)

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7541373

**Comment by aga11313** [comment]
@jakob1111996 check this ticket for progress

**Comment by aga11313** [comment]
@BastinJafari high priority as it is blocking 2.0 examples work

**Comment by aga11313** [comment]
Closing
