### ISSUE TITLE
Experimenting with cypress dashboard for debugging

### ISSUE THREAD

**Issue by lusloher** [jina-ai/dashboard#340]
This is a research ticket.

<p></p>

An integration test is failing that is succeeding on my machine. This ticket includes investigating the problem and proposing solutions.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200498922555298/1200500933835997) by [Unito](https://www.unito.io)

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/8318910

**Comment by aga11313** [comment]
Closing
