### ISSUE TITLE
🎨 fix style of settings menu

### ISSUE THREAD

**Issue by Roshanjossey** [jina-ai/dashboard#360]
This is the component that should be fixed.

![image](https://user-images.githubusercontent.com/8488446/131704531-e992769d-8f04-4fb8-b36e-6e00279f2787.png)
It should be fixed as below
![image](https://user-images.githubusercontent.com/8488446/131704868-d1d79487-c5f2-4997-804d-7d5f5f55fa76.png)

You can find the right styles implemented in https://dashboard.jina.ai/#/settings

## 💻  How to run this project locally

1. Fork this repository by clicking on fork button on the top right. This will create a copy of this repository on your account.
2. Clone your fork.
Get the URL of your fork by clicking on `code` button on GitHub.
Clone it to your local with command `git clone <URL you copied>`

    `git clone <https://github.com/><your-username>/dashboard.git`.

3. Install dependencies using command `npm i`.
```
cd dashboard
npm i
```
4. Run dashboard via the following ways .

### Run in the debug mode

 `npm run dev`

    Dashboard will be served on `http://localhost:3000` by default

## 🏃‍♀️ How to get there.
Click on the option `Settings` from the sidebar on the left

The component of interest is [Settings.tsx](https://github.com/jina-ai/dashboard/blob/master/src/components/Settings/Settings.tsx)

## 📝 Where to make changes?

https://github.com/jina-ai/dashboard/blob/master/src/components/Settings/Settings.tsx

## 🖐️ I want to work on this.

If you're interested in working on this issue, please write a comment down below. 💬

**Comment by vj-codes** [comment]
@Roshanjossey IG this should be closed since the PR is merged :)
For a minute even I thought it was available

**Comment by Roshanjossey** [comment]
Hey @vj-codes, yeah, this is done. I'll close this now. I'll ping you on slack when I draft new issues.
