### ISSUE TITLE
🎨 fix style: icons unaligned in filter select

### ISSUE THREAD

**Issue by Roshanjossey** [jina-ai/dashboard#361]
This is the component that should be fixed.

![image](https://user-images.githubusercontent.com/8488446/131753433-fa073ea1-5ee8-49a0-9a67-11a254a6f669.png)
It should be fixed as below

![image](https://user-images.githubusercontent.com/8488446/131753765-e272baed-b74c-40f5-bb8a-e5955dbb0c81.png)

You can find the right styles implemented in https://dashboard.jina.ai/

## 💻  How to run this project locally

1. Fork this repository by clicking on fork button on the top right. This will create a copy of this repository on your account.
2. Clone your fork.
Get the URL of your fork by clicking on `code` button on GitHub.
Clone it to your local with command `git clone <URL you copied>`

    `git clone <https://github.com/><your-username>/dashboard.git`.

3. Install dependencies using command `npm i`.
```
cd dashboard
npm i
```
4. Run dashboard via the following ways .

### Run in the debug mode

 `npm run dev`

    Dashboard will be served on `http://localhost:3000` by default

## 🏃‍♀️ How to get there.
You can find it in the home page.

The component of interest is [LogsTable.tsx](https://github.com/jina-ai/dashboard/blob/master/src/components/LogStream/LogsTable.tsx)

## 📝 Where to make changes?

https://github.com/jina-ai/dashboard/blob/master/src/components/LogStream/LogsTable.tsx

Please use [TailwindCSS](https://tailwindcss.com/docs) for styling as much as you can.

## 🖐️ I want to work on this.

If you're interested in working on this issue, please write a comment down below. 💬

**Comment by AleenaSA** [comment]
Hi, interested to work on this!

**Comment by Roshanjossey** [comment]
Hi @AleenaSA, sure, go ahead. Feel free to ask questions or get help.

**Comment by AleenaSA** [comment]
yeah a quick question, is it just the icon alignment you're looking for or the margin between the elements as well?

**Comment by Roshanjossey** [comment]
That would be nice too. Feel free to make any general changes that would improve the experience.
