### ISSUE TITLE
🎨 fix style: Logs table header

### ISSUE THREAD

**Issue by Roshanjossey** [jina-ai/dashboard#362]
This is the component that should be fixed.
![image](https://user-images.githubusercontent.com/8488446/131756336-4f8ce37e-9929-4b35-b675-daccf29cdf72.png)

It should be fixed as below

![image](https://user-images.githubusercontent.com/8488446/131756479-32e430d0-d5d1-4297-b223-bce178f83681.png)

You can find the right styles implemented in https://dashboard.jina.ai/

## 💻  How to run this project locally

1. Fork this repository by clicking on fork button on the top right. This will create a copy of this repository on your account.
2. Clone your fork.
Get the URL of your fork by clicking on `code` button on GitHub.
Clone it to your local with command `git clone <URL you copied>`

    `git clone <https://github.com/><your-username>/dashboard.git`.

3. Install dependencies using command `npm i`.
```
cd dashboard
npm i
```
4. Run dashboard via the following ways .

### Run in the debug mode

 `npm run dev`

    Dashboard will be served on `http://localhost:3000` by default

## 🏃‍♀️ How to get there

You can find it in the home page

The component of interest is [LogsTableHeader.tsx](https://github.com/jina-ai/dashboard/blob/master/src/components/LogStream/LogsTableHeader.tsx)

## 📝 Where to make changes?

https://github.com/jina-ai/dashboard/blob/master/src/components/LogStream/LogsTableHeader.tsx

Please use [TailwindCSS](https://tailwindcss.com/docs) for styling as much as you can.

## 🖐️ I want to work on this.

If you're interested in working on this issue, please write a comment down below. 💬

**Comment by sauravgarg540** [comment]
I would like to work on this issue

**Comment by vj-codes** [comment]
@sauravgarg540 hey are you still working on this? If not, I would like to give it a try!

**Comment by sauravgarg540** [comment]
Hey @vj-codes, I will be working on this issue and I am waiting for @Roshanjossey to assign this issue to me.

**Comment by Roshanjossey** [comment]
You don't have to wait for me. You can start working

**Comment by sauravgarg540** [comment]
#368

**Comment by Roshanjossey** [comment]
Fixed in #368
