### ISSUE TITLE
Hub images tab fails to load

### ISSUE THREAD

**Issue by freddyheppell** [jina-ai/dashboard#386]
**Describe the bug**
Going on the Hub tab on the hosted version of Jina Dashboard no longer shows hub images, because the `https://hubapi.jina.ai/images` endpoint is returning an internal server error. 

I know this isn't strictly an issue with Dashboard itself, but I can't find anywhere else to report it - I tried to join the Slack but it seems like the invite link no longer works.

**Comment by nomagick** [comment]
I thought this project was long deprecated.
Even jinad is deprecated.

@nan-wang Should we set this repo deprecated?
