### ISSUE TITLE
add auto-tag action for better maintain the issues and PRs

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/dashboard#4]

**Comment by Roshanjossey** [comment]
I think [hacktoberfest tagging](https://github.com/jina-ai/dashboard/blob/master/.github/workflows/hacktoberfest.yml) might not be in  the best interest of maintainers.

All issues created here will get labelled as hacktoberfest even if those issues might not be ready for community to start working on. This could be discouraging for people who might be interested to contribute.

**Comment by nan-wang** [comment]
@Roshanjossey Thanks for your comments. Definitely, adding more meaningful tags on the roadmap.
