### ISSUE TITLE
⚗️ Create integration tests

### ISSUE THREAD

**Issue by Roshanjossey** [jina-ai/dashboard#68]
**Problem**

Currently, this project has jest setup to do unit tests but there is no tool to do integration tests.

**Goal**

Have integration, end-to-end tests to make sure that the components work together. This will give us more confidence in releasing. We are now using [cypress](https://cypress.io) for integration tests.

**Next steps**
We'll create issues to help community tackle this. It would be a good way for new people to start engaging with this project too.
I'll maintain a list of issues we create on this topic.

- [ ]  [LogsTable](https://github.com/jina-ai/dashboard/issues/110)
- [ ]  [help view](https://github.com/jina-ai/dashboard/issues/111)

**Comment by imsergiy** [comment]
Thanks for bringing this up Roshan, we have plans to roll out a common testing framework throughout our frontend projects (Dashboard, Jinabox). Cypress seems like a great solution, I will look further into this and determine how well this would fit into our entire stack and the next steps for implementation.

**Comment by Roshanjossey** [comment]
With https://github.com/jina-ai/dashboard/pull/75, we're starting to use cypress.

Next steps:
1. Add cypress to CI 
2. Add tests to cover existing views.
