### ISSUE TITLE
[Bug] Linter for css and scss files broken

### ISSUE THREAD

**Issue by BastinJafari** [jina-ai/dashboard#73]
How to reproduce:

- pull the current master
- switch to a new branch
- change a CSS or SCSS file
- commit

![image](https://user-images.githubusercontent.com/25417797/97812747-c36e2080-1c83-11eb-8803-f8224fc9385f.png)

**Comment by Buffettt** [comment]
Hello. I could help you with this :)

**Comment by nan-wang** [comment]
> Hello. I could help you with this :)

hi, @Buffettt That would be great! Looking forward to your PR!

**Comment by seraco** [comment]
I opened a pull request (#82) that addresses this issue. I hope it helps.

**Comment by imsergiy** [comment]
https://github.com/jina-ai/dashboard/pull/82
