### ISSUE TITLE
broken task page view for some screen sizes

### ISSUE THREAD

**Issue by seraco** [jina-ai/dashboard#85]
As it can be seen in the next screenshots (768 x 1024 pixels and 320 x 568 pixels respectively), the home page view is broken for certain screen sizes:

![Screenshot 2020-12-08 201103](https://user-images.githubusercontent.com/25517036/101530400-26915800-3992-11eb-942d-bb31b540319d.png)
![Screenshot 2020-12-08 201213](https://user-images.githubusercontent.com/25517036/101530411-2a24df00-3992-11eb-814a-a07a760aeaef.png)

The following issues are observed:

* _Progress_ chart falls outside of its card in some screens.
* _Network Load_ chart does not properly display for certain screen sizes.

**Comment by imsergiy** [comment]
https://github.com/jina-ai/dashboard/pull/86
