### ISSUE TITLE
Change relative log streaming to absolute

### ISSUE THREAD

**Issue by BastinJafari** [jina-ai/dashboard#94]
The way Google Analytics handles log streaming is in an absolute  time frame:

![PoliticalFantasticBluebottle-small](https://user-images.githubusercontent.com/25417797/103669822-1eb8d980-4f79-11eb-8244-24e062f86184.gif)

But our logging time frame is relative:

https://user-images.githubusercontent.com/25417797/103669709-fb8e2a00-4f78-11eb-87c6-587181c57f96.mov

I would suggest to change that to the way google handles it.

**Comment by Roshanjossey** [comment]
Fixed in #101
